### ISSUE TITLE
Besteht die Möglichkeit den Anzeige-Stil der Kartendarstellung zu optimieren?

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/map-server-config#1]
Bei der neuen Map ist "OSM-Standard" für den Default-Karten-Renderer eingestellt. Hierdurch werden auf der Karte neben den Freifunk Knoten noch viele weitere Informationen zusätzlich dargestellt. Leider ist diese manchmal extremst störend.

Kann ich meinen Browser (Chrome) irgendwie überreden, einen anderen Karten-Renderer als den voreingestellten "OSM-Standard" zu verwenden? Mir ist klar, dass das seitenspezifisch ist, aber evtl. gibt es da einen kleinen Trick.

Oder könnte evtl. die Map so umgestellt werden, dass einen informationsärmeren Renderer wie z.B. "MapQuest" als Default verwendet wird?

Folgend zwei identische Kartenausschnitte (mit jeweils zwei Routern), aber unterschiedlich gerendert:

1) **OSM-Standart** (Hopglass-Default)
![osm_standard](https://cloud.githubusercontent.com/assets/1434390/15402491/bda7d5de-1df4-11e6-9730-0f733ad43342.png)

2) **MapQuest**
![mapquest](https://cloud.githubusercontent.com/assets/1434390/15402506/ceca3762-1df4-11e6-8416-9c0963149cc8.png)

P.S.
Ist nur ein Beispiel. Ich bin in keiner Partei :o)

**Comment by eberhab** [comment]
Einen Trick das lokal einzustellen kenne ich nicht. Ich würde das in der map config mal umstellen und die Diskussion hier aber noch eine Weile offen lassen für andere.

**Comment by eberhab** [comment]
bei Bedarf wieder öffnen

**Comment by t-8ch** [comment]
Habt ihr mal rechts unten auf den `Ebenen` Knopf geklickt?

**Comment by eberhab** [comment]
Ich verstehe nicht was du meinst. Könntest du etwas ausführlicher beschreiben was du uns sagen möchtest? Ich vermute schon, dass oszilloskop den Ebenen Knopf verwendet hat um die beiden Screenshots oben zu erzeugen. So wie ich es verstanden haben ging es ihm aber darum mapquest als default einzustellen. Sofern es da keine gegenstimmen gibt hab ich da kein problem mit. Daher ist der Fall bis auf Weiteres erstmal geklärt, no?

**Comment by eberhab** [comment]
wir müssen das ggf noch einmal ändern: https://github.com/plumpudding/hopglass/commit/20f0f08de35b250bcebb57617fb4bf7ce8f290aa

**Comment by eberhab** [comment]
MapQuest wird es bald nicht mehr geben. Ich würde vorschlagen, dass wir ebenfalls osm-humanitarian als standard übernehmen. Eine Liste der Verfügbaren leaflets gibt es hier:

http://leaflet-extras.github.io/leaflet-providers/preview/index.html

Ich habe ebenfalls stamen.tonerlight hinzugefügt.

Andere Wünschen/ Vorschläge?

**Comment by eberhab** [comment]
Zusatz zur ursprünglichen Frage: mein browser merkt sich übrigens was ich unter "Ebenen" angeklickt habe.

**Comment by eberhab** [comment]
nicht alle leaflet provider unterstützen ssl, daher gibt es mit MapQuest und auch mit osm.hot die warnung, dass "unsicherer" content nachgeladen werden muss.

Die aktuell eingebundenen provider welche ssl unterstützen sind: mapnik, stamen und esri.

Das könnte ein Argument dafür sein doch wieder mapnik als default zu nehmen, sonst präsentieren wir jedem map besucher direkt eine sicherheitswarnung :)

**Comment by t-8ch** [comment]
https://www.mapbox.com/pricing/
Oder wir hosten unsere eigenen Tiles, wir brauchen ja nur Frankfurt und davon ein paar Zoomstufen

**Comment by eberhab** [comment]
Macht Ihr Eure issues bitte mal wieder zu wenn Ihr keinen Bedarf an weiterer Diskussion habt, danke.
